# This Dockerfile builds the quatradis base image with all main dependencies which are not
# dependent on any other source code.  Using this image as the base provides a big speed up
# when building and testing quatradis.
FROM debian:bullseye-slim

# Install the system dependencies
RUN apt-get update -qq && \
    apt-get install -y sudo bzip2 curl default-jre gcc gzip locales make procps unzip wget && \
    apt-get install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common && \
    apt-get install -y bwa minimap2 smalt

# Setup R
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' && \
	add-apt-repository 'deb http://cloud.r-project.org/bin/linux/debian bullseye-cran40/' && \
	apt-get update -qq && \
	apt-get install -y r-base

# Install R dependencies
RUN Rscript -e "install.packages('BiocManager')" -e "BiocManager::install()" -e "BiocManager::install(c('edgeR','getopt', 'MASS'))"

# Install HTSlib to get bgzip installed as an executable
RUN wget https://github.com/samtools/htslib/releases/download/1.3.2/htslib-1.3.2.tar.bz2 -O htslib.tar.bz2 && \
    tar -xjvf htslib.tar.bz2 && \
    cd htslib-1.3.2 && \
    make && \
    make install && \
    rm /htslib.tar.bz2 && rm -r /htslib-1.3.2

# Install snakemake
# Set locales (required for running in Singularity)
RUN sed -i -e 's/# \(en_GB\.UTF-8 .*\)/\1/' /etc/locale.gen && \
    touch /usr/share/locale/locale.alias && \
    locale-gen
ENV LANG     en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL   en_GB.UTF-8
ENV SHELL /bin/bash
ENV PATH /opt/conda/bin:${PATH}

RUN /bin/bash -c "curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh"
RUN /bin/bash -c "conda install -y -c conda-forge mamba && \
    mamba create -q -y -c conda-forge -c bioconda -n quatradis python=3.10 snakemake snakemake-minimal && \
    source activate quatradis && \
    mamba install -q -y -c conda-forge -c bioconda snakemake snakemake-minimal && \
    mamba install -q -y -c conda-forge singularity && \
    conda clean --all -y && \
    which python"

RUN echo "source activate quatradis" > ~/.bashrc
ENV PATH /opt/conda/envs/quatradis/bin:/home/quatradis/.local/bin:${PATH}
RUN pip install cython pysam pytest-cov semantic-version matplotlib scipy