#!/usr/bin/env python3

import argparse

from quatradis.tags import tags_in_alignment


def main():
    parser = argparse.ArgumentParser(description=
                                     'Check for the existence of tradis tags in a sam/bam/cram file.')
    parser.add_argument('mapped_reads', type=str,
                        help='A SAM/BAM/CRAM file to check for tradis tags')

    args = parser.parse_args()

    present = tags_in_alignment(args.mapped_reads)
    print(present)


if __name__ == '__main__':
    main()
