#!/usr/bin/env python3

import argparse

from quatradis.isp_combine import combine


def main():
    parser = argparse.ArgumentParser(description=
                                     'Combine multiple tradis plot files into one.  Also can combine plots files in groups. ' +
                                     'The plot combining process is controlled via a tab-delimited file with an ID as the ' +
                                     ' first column followed by a list of plotfiles to combine per row. The ID will be used ' +
                                     ' to name the new plotfile and as an identifier in the stats file, so ensure these are unique.')
    parser.add_argument('plot_file_list', type=str,
                        help='A tab delimited file with id in the first column followed by a list of plot files')
    parser.add_argument('--combined_dir', dest='combined_dir', default="combined",
                        help='The directory in which to store the combined output files (default: combined)')

    args = parser.parse_args()

    combine(args.plot_file_list, args.combined_dir)


if __name__ == '__main__':
    main()
