#!/usr/bin/env python3

import argparse

from quatradis.isp_create import plot


def main():
    parser = argparse.ArgumentParser(description=
                                     'Create insertion site plot file from mapped reads')
    parser.add_argument('mapped_reads', type=str,
                        help='A SAM/BAM/CRAM file to check for tradis tags')
    parser.add_argument('-m', '--mapping_score', type=str, default=30,
                        help='mapping quality must be greater than X (Default: 30)')
    parser.add_argument('--outfile', default="tradis.plot",
                        help='Output file base name for plot (Default: tradis.plot)')

    args = parser.parse_args()

    plot(args.mapped_reads, plot_out_prefix=args.outfile, cutoff_score=args.mapping_score)


if __name__ == '__main__':
    main()
