name: Feature Branch CI

on:
  push:
    branches-ignore: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and test the Docker image
        run: docker build . --file Dockerfile --tag sbastkowski/quatradis:$(date +%s)

